# Generated by Django 4.2.3 on 2024-01-02 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deepfake", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myfileupload",
            old_name="file",
            new_name="myfile",
        ),
    ]
